### ISSUE TITLE
(Help Wanted) Click Events

### ISSUE THREAD

**Issue by DawidvanGraan** [xieziyu/angular2-echarts#1]
Hi, I need some help in registering for click events on the chart. Currently I'm display the chart and adding `MarkPoints`, when a user clicks on a marker I want to open a new page with the information display. I'm not sure how to register for the click events from the chart.

Thanks in advance,
Dawid

**Comment by xieziyu** [comment]
@DawidvanGraan glad to know that you need this feature. The output event feature is in the plan. Now I will make it easy to register the click events ASAP.

**Comment by DawidvanGraan** [comment]
@xieziyu Awesome! That will be great, thank you very much!

**Comment by xieziyu** [comment]
Hi @DawidvanGraan ,
Please upgrade to v1.1.0. Now it supports the mouse events. I also updated the [demo](https://xieziyu.github.io) page and README.md.

You can now bind to the click events just like:
```html
<div echarts [options]="chartOptions" (chartClick)="onChartClick($event)" class="demo-chart"></div>
```
And check the params in the component just like:
```javascript
onChartClick(params: any) {
  if (params.componentType == "markPoint") {
    // do something you want ...
  }
}
```

Hope this could help you.

BRs,
Ziyu

**Comment by DawidvanGraan** [comment]
Excellent @xieziyu! Working like a charm!! Thank you very much for adding to so quick!
