### ISSUE TITLE
初始化主题

### ISSUE THREAD

**Issue by zxdmrg** [xieziyu/angular2-echarts#10]
这里可以初始化主题吗？用echart主题构建里面下载的主题js

**Comment by xieziyu** [comment]
@zxdmrg 最新的v1.1.7版本支持

先在`.angular-cli.json`文件中引入主题JS文件，如`dark.js`：
```javascript
"scripts": [
    "../node_modules/echarts/dist/echarts.js",
    "../theme/dark.js",
]
```

然后在echarts的html上，指定theme属性：
```html
<div echarts theme="dark" [options]="chartOption" class="demo-chart"></div>
```

**Comment by zxdmrg** [comment]
@xieziyu 按照你的说明修改了，但是没有生效。确定已经升级到1.1.7了

**Comment by xieziyu** [comment]
@zxdmrg 我的demo页上已经放了带dark主题的示例，说明组件本身是正常工作的。
你的主题是官方的主题还是自己构建的主题？主题文件中有没有调用`echarts.registerTheme`，并且注册的名字和theme绑定的名字相同？

方便地话可以贴一下json配置和网页代码看看

**Comment by zxdmrg** [comment]
@xieziyu  非常感谢，我注册的theme和文件取的名字不一样。更改过来就可以了。
