### ISSUE TITLE
XHR error 404 Not Found

### ISSUE THREAD

**Issue by EliechCai** [xieziyu/angular2-echarts#11]
我用的是quickstart，在index里引入了echarts.js，也在app.module里添加了AngularEchartsModule，但是刚添加上控制台就报了这个错误，后台也只有404，没有其他报错，是需要在别的地方比如说修改systemjs.config么？

**Comment by xieziyu** [comment]
@Eletch 请更新到`angular2-echarts` v1.2.0版本，然后按照README中关于SystemJS的配置方式，修改systemjs.config.js文件

这种情况下，不需要在index.html里面引用echarts.js

**Comment by EliechCai** [comment]
谢谢了
