### ISSUE TITLE
Jhipster项目中如何导入echarts图啊，急，求解答，谢谢！

### ISSUE THREAD

**Issue by pppzhou** [xieziyu/angular2-echarts#12]
用Jhipster建的项目，前端是angular2的，想在其中导入echarts图，echarts 和angular2-echarts也安装了，但是跑项目的时候一直说echart is not defined ，是哪里导错了吗？求解，谢谢！

**Comment by xieziyu** [comment]
@pppzhou 项目中是否使用了angular-cli做配置项？

**Comment by pppzhou** [comment]
恩，是的，"scripts": ["../node_modules/echarts/dist/echarts.js"]，这样也导入了。

**Comment by xieziyu** [comment]
@pppzhou 方便贴一下angular-cli里面的配置和你的目录结构吗？

**Comment by pppzhou** [comment]
https://github.com/pppzhou/Jhispter
我把完整项目传到git上了，项目结构是用jhipster自动生成的，比较大。进入src/main/webapp/app/entities/book这个目录下，echarts的相关改动都在这里了。

**Comment by xieziyu** [comment]
@pppzhou 看到了你的项目，虽然使用了angular-cli，但实际编译npm的脚本用的还是webpack，所以应该需要在webpack的配置中引用echarts。

我本地无法正常编译你的项目，所以需要你试一下在`webpack.common.js` 中的`ProvidePlugin`配置里面添加echarts的定义：
```javascript
new webpack.ProvidePlugin({
  $: "jquery",
  jQuery: "jquery",
  // add this:
  echarts: "echarts"
}),
```

**Comment by pppzhou** [comment]
@xieziyu 非常感谢，今天早上试了下，图可以显示了。
