### ISSUE TITLE
legend.data not changed

### ISSUE THREAD

**Issue by txone** [xieziyu/angular2-echarts#3]
legend.data

**Comment by txone** [comment]
type:'pie'

**Comment by xieziyu** [comment]
@TxOne As angular2 only checks the object reference, I think you need to update your options binding before (or after) your legend.data.

Try this:
```javascript
// update the options
this.options = Object.assign({}, this.options);

// then change the legend data:
this.options.legend.data = [{ ... }];
```

Hope this could help you :)
BRs,
Ziyu
