### ISSUE TITLE
Canvas not resizing when closing a side menu

### ISSUE THREAD

**Issue by averhaegen** [xieziyu/angular2-echarts#7]
Hi,

I'm having trouble to get the chart responsive on my website. I have a side menu that can be opened and closed. The chart will only resize if I resize the complete window or if the page is reloaded.

Is it possible to manually refresh the chart (so the correct dimensions are loaded) or can you update this package and set the canvas to 100% width instead of a fixed size? The canvas is placed inside a div that is responsive.

Thanks!

![image](https://cloud.githubusercontent.com/assets/18397987/25484826/c96c0500-2b5b-11e7-982a-f228bc95edc2.png)
![image](https://cloud.githubusercontent.com/assets/18397987/25484909/2059208c-2b5c-11e7-9238-ada07c8e0344.png)

**Comment by xieziyu** [comment]
Hi @averhaegen ,

I've published v1.1.6. It now exposes `echartsInstance` in `chartInit` event. So you can manually call `echartsInstance.resize()` method to fix it!

And thanks for your supports.

**Comment by averhaegen** [comment]
@xieziyu Thank you very much!

I got it working now. I used an rxjs Subject that will fire an event if the side menu is toggled. The event will then trigger the resize method.
