### ISSUE TITLE
Add 'dataZoom' event

### ISSUE THREAD

**Issue by averhaegen** [xieziyu/angular2-echarts#8]
Hello again,

Can you please update this package to support the 'dataZoom' event?
Maybe you can add the other events too, in case somebody needs them in the future..

Thanks!

EDIT: I made a fork of this repo and added the dataZoom myself. I also made a pull request: https://github.com/xieziyu/angular2-echarts/pull/9

**Comment by xieziyu** [comment]
Hi @averhaegen ,

Great, thank you! I've merged your PR.
